# Livro para consulta:
- https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html
- https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html

# 1. Importando bibliotecas <a name="import"></a>

<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

# 2. Carregando o dataframe SINASC <a name="read"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [3]:
sinasc_raw = pd.read_csv('SINASC_RO_2019.csv')
sinasc_raw.head()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,1,2679477.0,110001,1,19,5.0,8 a 11 anos,NaN,0.0,0.0,...,5,1,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
1,1,2679477.0,110001,1,29,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,2,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
2,1,2679477.0,110001,1,37,9.0,8 a 11 anos,513205.0,2.0,0.0,...,5,3,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025

In [4]:
sinasc_raw.columns

Index(['ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE', 'ESTCIVMAE',
       'ESCMAE', 'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'CODMUNRES',
       'GESTACAO', 'GRAVIDEZ', 'PARTO', 'CONSULTAS', 'DTNASC', 'HORANASC',
       'SEXO', 'APGAR1', 'APGAR5', 'RACACOR', 'PESO', 'IDANOMAL', 'DTCADASTRO',
       'CODANOMAL', 'NUMEROLOTE', 'VERSAOSIST', 'DTRECEBIM', 'DIFDATA',
       'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU', 'ESCMAE2010',
       'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT', 'QTDPARTNOR',
       'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC', 'TPMETESTIM',
       'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART', 'STCESPARTO',
       'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC', 'ESCMAEAGR1',
       'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON', 'PARIDADE',
       'KOTELCHUCK', 'CONTADOR', 'munResStatus', 'munResTipo', 'munResNome',
       'munResUf', 'munResLat', 'munResLon', 'munResAlt', 'munResArea'],
      dtype='object')

In [5]:
sinasc_raw['munResNome']

0          Alta Floresta D'Oeste
1          Alta Floresta D'Oeste
2          Alta Floresta D'Oeste
3        Alto Alegre dos Parecis
4          Alta Floresta D'Oeste
                  ...
27023                    Vilhena
27024                Chupinguaia
27025                    Vilhena
27026                    Vilhena
27027    Novo Horizonte do Oeste
Name: munResNome, Length: 27028, dtype: object

# Tarefa 1

### 1. Idade media das mães e dos pais por município (coluna munResNome)

In [6]:
sinasc_1 = sinasc_raw[['munResNome' ,'IDADEMAE', 'IDADEPAI']]
sinasc_1.groupby('munResNome').mean().sort_values(by=['IDADEPAI'])

                            IDADEMAE   IDADEPAI
munResNome
Município ignorado - RO    24.000000  22.000000
Rio Crespo                 26.660000  28.000000
Alto Paraíso               24.960177  28.833333
Alto Alegre dos Parecis    24.844156  29.179104
Governador Jorge Teixeira  24.401786  29.222222
Alta Floresta D'Oeste      25.991826  29.548701
Chupinguaia                25.333333  29.629630
Pimenta Bueno              25.199675  29.745174
Candeias do Jamari         25.243323  29.894737
Vale do Paraíso            25.679012  29.976744
Theobroma                  25.536082  30.083333
Presidente Médici          25.796053  30.150754
Rolim de Moura             26.600863  30.360479
Castanheiras               27.281250  30.392857
Guajará-Mirim              25.462228  30.470588
Campo Novo de Rondônia     24.825301  30.500000
Seringueiras               24.910714  30.500000
Nova Brasilândia D'Oeste   26.222222  30.520833
Costa Marques              24.412017  30.613636
Santa Luzia D'Oeste        26.121212  30.703297
Alvorada D'Oeste           25.770732  30.757282
Buritis                    25.559177  30.812500
Cacoal                     26.890102  30.931854
Urupá                      26.688235  31.008929
Ji-Paraná                  26.361137  31.132239
Espigão D'Oeste            26.093333  31.198113
Ouro Preto do Oeste        26.375594  31.233244
Machadinho D'Oeste         25.480000  31.326923
Nova União                 26.894231  31.371429
São Felipe D'Oeste         26.481481  31.395833
Cujubim                    24.482927  31.400000
Teixeirópolis              26.031250  31.500000
Novo Horizonte do Oeste    26.938776  31.588235
São Francisco do Guaporé   25.660066  31.638889
Cerejeiras                 27.240506  31.652778
Nova Mamoré                25.326389  31.692308
Primavera de Rondônia      27.023256  31.888889
Mirante da Serra           26.304878  32.154762
Jaru                       25.982974  32.197183
Porto Velho                26.312670  32.352679
Ariquemes                  25.607866  32.466667
Corumbiara                 24.716535  32.470588
Parecis                    26.454545  32.473684
São Miguel do Guaporé      25.926346  32.666667
Ministro Andreazza         27.904762  33.849315
Vale do Anari              26.096774  34.000000
Vilhena                    26.433962  34.152941
Cabixi                     26.037500  34.333333
Colorado do Oeste          27.602804  34.354839
Monte Negro                25.648241  34.678571
Pimenteiras do Oeste       25.075000  35.600000
Cacaulândia                25.546667  36.333333
Itapuã do Oeste            26.064220  42.500000

### 2. Peso médio dos bebes por sexo que nasceram no dia do seu aniversário por faixas de escolaridade mae
Ex: Você, aluna(o), nasceu no dia 10/01, então você precisa filtrar o conjunto de dados nessa data e calcular o peso médio dos bebês de cada sexo por faixa de escolaridade da mãe.

In [7]:
sinasc_2 = sinasc_raw[['DTNASC','PESO', 'SEXO',  'ESCMAE']]
sinasc_2.loc[sinasc_2['DTNASC'] == '2019-06-28'].groupby(['ESCMAE', 'SEXO'])['PESO'].mean().to_frame()

                                  PESO
ESCMAE          SEXO
1 a 3 anos      Masculino  3462.000000
12 anos ou mais Feminino   3081.000000
                Masculino  3280.800000
4 a 7 anos      Feminino   3307.125000
                Masculino  3293.375000
8 a 11 anos     Feminino   3158.076923
                Masculino  3205.241379

### 3. Qual o municipio que nasceu menos bebe em 2019?
    - qual a idade media, maxima, minima das maes nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [8]:
sinasc_3 = sinasc_raw[['IDADEMAE','munResNome', 'IDADEPAI', 'SEXO']].copy()
sinasc_3.groupby(['munResNome'])['SEXO'].count().to_frame().sort_values(by='SEXO')

                           SEXO
munResNome
Município ignorado - RO       1
Castanheiras                 32
Pimenteiras do Oeste         40
Primavera de Rondônia        43
Parecis                      44
Rio Crespo                   50
São Felipe D'Oeste           54
Teixeirópolis                64
Cacaulândia                  75
Cabixi                       80
Vale do Paraíso              81
Ministro Andreazza           84
Vale do Anari                93
Theobroma                    97
Novo Horizonte do Oeste      98
Santa Luzia D'Oeste          99
Nova União                  104
Itapuã do Oeste             109
Governador Jorge Teixeira   112
Corumbiara                  127
Alto Alegre dos Parecis     154
Chupinguaia                 162
Mirante da Serra            164
Campo Novo de Rondônia      166
Seringueiras                168
Urupá                       170
Monte Negro                 199
Cujubim                     205
Alvorada D'Oeste            205
Colorado do Oeste           214
Alto Paraíso                226
Costa Marques               233
Cerejeiras                  237
Nova Brasilândia D'Oeste    261
São Francisco do Guaporé    302
Presidente Médici           304
Candeias do Jamari          337
São Miguel do Guaporé       353
Alta Floresta D'Oeste       367
Nova Mamoré                 432
Espigão D'Oeste             450
Machadinho D'Oeste          500
Buritis                     583
Pimenta Bueno               616
Ouro Preto do Oeste         631
Guajará-Mirim               781
Jaru                        881
Rolim de Moura              927
Cacoal                     1374
Vilhena                    1590
Ariquemes                  1729
Ji-Paraná                  2181
Porto Velho                8435

In [9]:
sinasc_3.loc[sinasc_3['munResNome'] == 'Castanheiras'].groupby('munResNome').agg({'IDADEMAE': ['min','mean','max'],
                                                                                   'IDADEPAI': ['min','mean','max']})

             IDADEMAE               IDADEPAI
                  min      mean max      min       mean   max
munResNome
Castanheiras       17  27.28125  39     17.0  30.392857  43.0

### 4. Qual o municipio que nasceu mais bebe no mês de março?
    - qual a quantidade de filhos vivos media, maxima, minima nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [10]:
sinasc_4 = sinasc_raw[['DTNASC','munResNome', 'IDADEMAE',  'IDADEPAI','SEXO', 'GRAVIDEZ','QTDFILVIVO', 'PARTO']].copy()
sinasc_4['DTNASC'] = pd.to_datetime(sinasc_4['DTNASC'])
marco = sinasc_4.loc[sinasc_4['DTNASC'].dt.month == 3]
marco.groupby(['munResNome'])['PARTO'].count().to_frame().sort_values(by='PARTO', ascending=False)

                           PARTO
munResNome
Porto Velho                  740
Ji-Paraná                    188
Vilhena                      148
Ariquemes                    141
Cacoal                       133
Jaru                          80
Guajará-Mirim                 75
Rolim de Moura                68
Ouro Preto do Oeste           67
Pimenta Bueno                 62
Buritis                       59
Nova Mamoré                   53
Espigão D'Oeste               44
Machadinho D'Oeste            44
São Miguel do Guaporé         41
Candeias do Jamari            33
São Francisco do Guaporé      31
Alta Floresta D'Oeste         30
Presidente Médici             29
Costa Marques                 24
Alvorada D'Oeste              22
Alto Paraíso                  22
Monte Negro                   20
Nova Brasilândia D'Oeste      20
Seringueiras                  19
Colorado do Oeste             19
Chupinguaia                   18
Cujubim                       17
Cerejeiras                    16
Urupá                         14
Vale do Paraíso               13
Campo Novo de Rondônia        13
Corumbiara                    12
Vale do Anari                 11
Alto Alegre dos Parecis       10
Cacaulândia                   10
Rio Crespo                     9
Mirante da Serra               9
Governador Jorge Teixeira      9
Theobroma                      8
Itapuã do Oeste                8
Santa Luzia D'Oeste            7
Nova União                     7
Cabixi                         6
Parecis                        6
Ministro Andreazza             6
Pimenteiras do Oeste           6
Primavera de Rondônia          5
São Felipe D'Oeste             5
Novo Horizonte do Oeste        5
Castanheiras                   4
Teixeirópolis                  3

In [11]:
sinasc_4.loc[sinasc_4['munResNome'] == 'Porto Velho'].groupby('munResNome').agg({'QTDFILVIVO': ['min','mean','max'],
                                                                            'IDADEMAE': ['min','mean','max'],
                                                                            'IDADEPAI': ['min','mean','max']})

            QTDFILVIVO                 IDADEMAE               IDADEPAI  \
                   min      mean   max      min      mean max      min
munResNome
Porto Velho        0.0  1.167236  12.0       12  26.31267  47     16.0


                  mean   max
munResNome
Porto Velho  32.352679  65.0

### Analise as respostas encontradas, tire algum insight delas, conte pra gente algo encontrado nos dados. Algo que você julgue relevante e novo pra você.

Exemplo:
- Ah, descobri que a idade mediana das mulheres que deram a luz no ano de 2019 dos municipios x é maior que y.

### Insight questão 1

Analisando a idade media de mães e pais entre os municipios é possivel afirmar que
a idade media de maes variam entre 24 e 27 anos enquanto a dos pais variam entre 28
e 34 anos com casos unicos de 22 anos sendo o minimo e de 35, 36 e 42 anos sendo o maximo.

### Insight questão 2

analisando o peso médio de bebes por sexo que nasceram nos dias 28-06-2019 por faixa de escolaridade da mae, podemos notar que as mães tem ao menos de 1 a 3 anos de escolaridade e que o bebê mais pesado é masculino e o menos pesado é feminino.

### Insight questão 3
ao analisar o municipio que nasceu menos bebes notamos um dado erroneo com apenas 1 contagem, vamos ignorar e iremos prosseguir com o municipio de Castanheiras que contem 32 bebes nascidos em 2019.
temos as medias de idade de mae sendo 27 e de pai sendo 30, enquanto a idade minima para ambos é de 17.

### Insight questão 4  *CORRIGIDA*

podemos analisar com os dados que temos, que a cidade de Porto Velho foi o municipio que mais teve bebes nascidos em março, com uma taxa minima de filhos vivos de 0.0 e maximo 12.0 vemos também que a idade minima das maes é de 12 e dos pais 16 anos. Notamos também que a idade maxima de pais é de 65 anos.

In [12]:
sinasc_raw.dtypes

ORIGEM          int64
CODESTAB      float64
CODMUNNASC      int64
LOCNASC         int64
IDADEMAE        int64
               ...
munResUf       object
munResLat     float64
munResLon     float64
munResAlt     float64
munResArea    float64
Length: 69, dtype: object

In [15]:
sinasc_raw.select_dtypes(exclude=['object']).columns

Index(['ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE', 'ESTCIVMAE',
       'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'CODMUNRES', 'CONSULTAS',
       'HORANASC', 'APGAR1', 'APGAR5', 'PESO', 'IDANOMAL', 'NUMEROLOTE',
       'DIFDATA', 'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU',
       'ESCMAE2010', 'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT',
       'QTDPARTNOR', 'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC',
       'TPMETESTIM', 'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART',
       'STCESPARTO', 'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC',
       'ESCMAEAGR1', 'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON',
       'PARIDADE', 'KOTELCHUCK', 'CONTADOR', 'munResLat', 'munResLon',
       'munResAlt', 'munResArea'],
      dtype='object')

In [14]:
sinasc_raw.columns

Index(['ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE', 'ESTCIVMAE',
       'ESCMAE', 'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'CODMUNRES',
       'GESTACAO', 'GRAVIDEZ', 'PARTO', 'CONSULTAS', 'DTNASC', 'HORANASC',
       'SEXO', 'APGAR1', 'APGAR5', 'RACACOR', 'PESO', 'IDANOMAL', 'DTCADASTRO',
       'CODANOMAL', 'NUMEROLOTE', 'VERSAOSIST', 'DTRECEBIM', 'DIFDATA',
       'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU', 'ESCMAE2010',
       'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT', 'QTDPARTNOR',
       'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC', 'TPMETESTIM',
       'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART', 'STCESPARTO',
       'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC', 'ESCMAEAGR1',
       'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON', 'PARIDADE',
       'KOTELCHUCK', 'CONTADOR', 'munResStatus', 'munResTipo', 'munResNome',
       'munResUf', 'munResLat', 'munResLon', 'munResAlt', 'munResArea'],
      dtype='object')